-- NSpecies
NDefines.NSpecies.MAX_ETHIC_POINTS = 4
NDefines.NSpecies.MAX_TRAIT_POINTS = 4
NDefines.NSpecies.MAX_TRAITS = 8

-- NCamera
NDefines.NCamera.SYSTEM_SPACE_SCALE_MULT = 40.0
NDefines.NCamera.GALAXY_SPACE_SCALE_MULT = 2.0

-- NGraphics
NDefines.NGraphics.MISSED_BEAM_LENGTH = 500.0
NDefines.NGraphics.SHIP_RANDOM_HEIGHT_OFFSET = 40.0
NDefines.NGraphics.MISSILE_HEIGHT_OFFSET = 27.5
NDefines.NGraphics.MISSILE_RANDOM_OFFSET_MIN_RADIUS = 0
NDefines.NGraphics.MISSILE_RANDOM_OFFSET_MAX_RADIUS = 0
NDefines.NGraphics.TRAILS_MISSILE_ALPHA_FADE = 3
NDefines.NGraphics.TRAILS_MISSILE_BASE_WIDTH = 2.0
NDefines.NGraphics.BALLISTIC_PROJECTILE_MISSED_LIFETIME = 5.0

-- NCombat
NDefines.NCombat.COMBAT_BACK_OFF_RATE = 0.375
NDefines.NCombat.COMBAT_DETECT_RANGE_MULT = 0.75
NDefines.NCombat.FLEET_MOVE_MAX_DIST_SHIPS = 150.0

-- NGameplay
NDefines.NGameplay.ETHOS_MAX_POINTS = 4
NDefines.NGameplay.NAVY_SIZE_MAX = 248376
NDefines.NGameplay.PLANET_ARMIES_LIMIT = 84
NDefines.NGameplay.VICTORY_CONDITION_DOMINATION = 0.95
NDefines.NGameplay.SECTOR_CAP = 5
NDefines.NGameplay.SECTOR_CAP_INCR = 0
-- NDefines.NGameplay.GOVERNMENT_COOLDOWN_YEARS = 0
-- NDefines.NGameplay.GOVERNMENT_CHANGE_INFLUENCE_COST = 0
-- NDefines.NGameplay.ALLOW_EMPIRE_DESIGN_CHEATS = true